style: add nprogress and change page loading
staketogether/st-interface pull request #19
Opened 2023-06-07 21:55 UTC by paulobarcelosbr

2023-06-08 15:38 UTC, arthurmr96 approved these changes

2023-06-08 20:47 UTC, 0xfabricio reviewed
Troca pra essa lib:
https://www.npmjs.com/package/nextjs-progressbar/v/0.0.16

Essa que você mandou é de 8 anos atrás

Atualiza o PR com a DEV

2023-06-09 19:08 UTC, arthurmr96 requested changes

2023-06-09 19:08 UTC, arthurmr96 commented on src/pages/_app.tsx
> +              <NextNProgress color='#7154b7' options={{ easing: 'ease', speed: 500 }} />
Essa cor pode ser pega do tema?

2023-06-09 20:06 UTC, arthurmr96 approved these changes

2023-06-09 20:16 UTC, 0xfabricio approved these changes

2023-06-09 20:16 UTC, merged